//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseWords
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int ID_Block { get; set; }
        public string Question1 { get; set; }
        public string Answer { get; set; }
    
        public virtual Block Block { get; set; }
    }
}
