//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseWords
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Word()
        {
            this.Users = new HashSet<User>();
        }
    
        public int ID_Word { get; set; }
        public string Name { get; set; }
        public string Translation { get; set; }
        public int ID_Block { get; set; }
        public int ID_Lesson { get; set; }
        public int ID_Stage { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual Sound Sound { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
