

CREATE TABLE Blocks
(
ID_Block INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(100)
);

CREATE TABLE Lessons
(
ID_Lesson INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(100)
);

CREATE TABLE Stages
(
ID_Stage INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(100)
);



CREATE TABLE Words
(
ID_Word INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(100),
Translation NVARCHAR(100),
ID_Block INT NOT NULL REFERENCES Blocks(ID_Block),
ID_Lesson INT NOT NULL REFERENCES Lessons(ID_Lesson),
ID_Stage INT NOT NULL REFERENCES Stages(ID_Stage)
);

CREATE TABLE Question
(
ID_Questin INT NOT NULL PRIMARY KEY IDENTITY(1,1),
ID_Block INT NOT NULL REFERENCES Blocks(ID_Block),
Question VARCHAR(100),
Answer VARCHAR(100)
);

CREATE TABLE Sounds
(
ID_Word INT NOT NULL REFERENCES Words(ID_Word),
NamePath VARCHAR(100),
);

CREATE TABLE Users
(
ID_Login VARCHAR(20) NOT NULL PRIMARY KEY,
Name VARCHAR(100),
UserPassword VARCHAR(100),
DateOfBirth date,
Mail VARCHAR(100),
AmoutOfBlock INT
);

CREATE TABLE LearntWords
(
ID_Word INT NOT NULL REFERENCES Words(ID_Word),
ID_Login VARCHAR(20) NOT NULL REFERENCES Users(ID_Login)

);